### ISSUE TITLE
`ng add ng2-charts@4.0.0` fails in an Angular 14 project

### ISSUE THREAD

**Issue by mraible** [valor-software/ng2-charts#1550] opened 2022-11-30 21:12 UTC
**Reproduction of the problem**

Create an app with JHipster v7.9.3 and Angular and try to add this library. You'll see a stack trace like the following:

```
Cannot find module '@angular/cdk/schematics'
Require stack:
- /Users/mraible/dev/21-points/node_modules/ng2-charts/schematics/ng-add/steps/add-ng2-charts-module.js
- /Users/mraible/dev/21-points/node_modules/ng2-charts/schematics/ng-add/setup-project.js
- /Users/mraible/dev/21-points/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/mraible/dev/21-points/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/mraible/dev/21-points/node_modules/@angular/cli/src/commands/add/cli.js
- /Users/mraible/dev/21-points/node_modules/@angular/cli/src/command-builder/command-runner.js
- /Users/mraible/dev/21-points/node_modules/@angular/cli/lib/cli/index.js
- /Users/mraible/.nvm/versions/node/v16.17.0/lib/node_modules/@angular/cli/lib/init.js
```

Workaround is to install the library above or use `npm install ng2-charts@4.0.0`.

**Comment by santam85** [comment] 2022-12-02 14:01
Duplicate of https://github.com/valor-software/ng2-charts/issues/1548
Which version of the library are you using? 
The cdk/schematics lib is actually a peer dependency of the library, so unless you use npm 8 you need to heed the warnings shown on install.

**Closed by santam85** 2022-12-02 14:01 UTC

**Comment by mraible** [comment] 2022-12-02 15:56
I'm using ng2-charts v4.0.0. 

```
➜  ~ node --version
v16.17.0
➜  ~ npm --version
8.19.3
```

**Comment by santam85** [comment] 2022-12-02 16:10
I'm sorry but can't reproduce the issue on a clean angular project with the npm version you specified. Have you added the library with 
`ng add ng2-charts`?
Have you got any warning during the npm install?

**Comment by mraible** [comment] 2022-12-02 16:36
You can see the issue if you generate a brand new JHipster 7.9.3 project. For example:

```
npm i -g generator-jhipster@7.9.3
mkdir demo && cd demo
jhipster jdl default
ng add ng2-charts # will fail because JHipster uses Angular 14
ng add ng2-charts@4.0.0 # fails because of issue above
npm i ng2-charts@4.0.0 # works
```

**Comment by santam85** [comment] 2022-12-02 20:02
the JHipster generator fails for me with:
`ERR_PACKAGE_PATH_NOT_EXPORTED`

**Comment by mraible** [comment] 2022-12-02 20:17
Are you using Node 18? I think that's what causes this error (https://github.com/jhipster/generator-jhipster/issues/19627). Node 16 should work.
