### ISSUE TITLE
Add support for Angular 17

### ISSUE THREAD

**Issue by dsubelman** [valor-software/ng2-charts#1771] opened 2023-11-21 15:18 UTC
Now that Angular 17 has been released, are there any plans to release a new version that supports Angular 17?

**Comment by santam85** [comment] 2023-11-23 11:46
It's WIP at https://github.com/valor-software/ng2-charts/tree/angular-17
There are currently issues with some of the upstream dependencies, the ESM build limitations (https://github.com/angular/angular-cli/issues/26368 17.1.0 should fix that), jest testing and some of the Chart.js plugins used in the demos.

**Comment by dsubelman** [comment] 2023-11-23 15:17
@santam85 thanks for the update and maintaining this project.

**Comment by basrieter** [comment] 2023-11-29 09:26
> The library will work correctly and should not throw any dependency warning with Angular 17.

So we can force upgrade to Angular 17 and it should keep working?

**Comment by sampath0606** [comment] 2023-12-05 11:46
I am getting the flowing error on trying to create/generate a chart using ng2-charts.
ng generate ng2-charts:pie Deptwise-pie  
ENOENT: no such file or directory, open 'D:\XXX\XX\apps-management\node_modules\ng2-charts\schematics\src\ng-generate\pie\files\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.html.template'

My package file:
![image](https://github.com/valor-software/ng2-charts/assets/36421369/18af6fa7-9cc9-41c3-bbe7-a210bb6fe787)


Could you please help ? @santam85 ( something similar to : https://github.com/valor-software/ng2-charts/issues/1368)

**Comment by santam85** [comment] 2023-12-05 13:07
@sampath0606 try v5.0.4

**Comment by sampath0606** [comment] 2023-12-05 13:21
http fetch GET 200 https://registry.npmjs.org/ng2-charts 33ms (from cache)
21 silly registry:manifest no matching version for ng2-charts@^5.0.4 in the cache. Forcing revalidation.
22 http fetch GET 304 https://registry.npmjs.org/ng2-charts 431ms (from cache)
23 silly fetchPackageMetaData error for ng2-charts@^5.0.4 No matching version found for ng2-charts@^5.0.4.

Is it available in the npm?

**Comment by sampath0606** [comment] 2023-12-05 13:24
12 http fetch GET 200 https://registry.npmjs.org/ng2-charts 1585ms
13 silly fetchPackageMetaData error for ng2-charts@5.0.4 No matching version found for ng2-charts@5.0.4.
14 timing stage:rollbackFailedOptional Completed in 2ms

i cleared my cache and tried to install 5.0.4 but din get it. Could you guide on how i can get that version? im using npm

**Comment by santam85** [comment] 2023-12-05 13:32
It was being released: https://github.com/valor-software/ng2-charts/actions/runs/7101446397 should be there now.

**Comment by sampath0606** [comment] 2023-12-05 14:00
The error is gone, but then when i used it to create a chart component there are issues with the classes(label, chartdatasets) and in html .

i have imported the chart module into my app and sub module too but of no help. @santam85 
![image](https://github.com/valor-software/ng2-charts/assets/36421369/9e619779-68a7-465a-b60e-5c1ab7d58c25)

**Comment by santam85** [comment] 2023-12-05 14:02
have you added the library with ng-add? you seem to be missing the module import. Feel free to open a PR if you find something missing in the generated templates.

**Comment by ElenaLj** [comment] 2024-02-09 11:05
Are there any news on the support for Angular 17?

**Comment by santam85** [comment] 2024-02-09 22:03
As said before, the current version of the library works perfectly with Angular 17, without any errors.
The PR to transition the library to build against Angular 17 (therefore making it incompatible with angular 16 and older) has been merged, ironing out the last kinks before releasing a new version, check the discussions on the open PRs.

> Are there any news on the support for Angular 17?

**Comment by santam85** [comment] 2024-02-15 15:37
v6.0.0-beta.1 is released, there are a few breaking changes done as a result of the upgrade. Please check the release notes and test.

**Comment by ManuViola77** [comment] 2024-02-16 02:40
I upgraded to v6 beta and I'm getting this error:

<img width="773" alt="image" src="https://github.com/valor-software/ng2-charts/assets/8755889/26e5d820-c1e6-4ef2-8ac5-2384d2c6a685">

**Comment by adrian-heath** [comment] 2024-02-18 23:07
I've updated to v6.0.0-beta.1 and followed the changes in the readme.  The charts are displaying however I get the following error in angular cli output every time the chart is rendered.  I am using SSR and es-build. Has anyone else experienced this error?

ERROR Error: NotYetImplemented
    at exports.nyi (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:474:13)
    at new _BaseChartDirective (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:27858:38)
    at NodeInjectorFactory.BaseChartDirective_Factory [as factory] (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:27963:10)
    at getNodeInjectable (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:6667:38)
    at instantiateAllDirectives (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:9061:23)
    at createDirectivesInstances (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:8653:3)
    at ɵɵelementStart (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:16415:5)
    at Module.ɵɵelement (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:16459:3)
    at DayGraphComponent_Conditional_2_Template (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:7167:27)
    at executeTemplate (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:8626:5)

Also the readme mentions using withColorGenerator however that doesn't seem to be exported from ng2-charts

**Comment by kjcordell** [comment] 2024-02-20 17:39
When trying to generate schematics using Angular 17, ng2-charts 5.0.4 and chart.js 4.4.1 and following this demo online: https://www.smashingmagazine.com/2020/07/responsive-dashboard-angular-material-ng2-charts-schematics/, and running the commands: ng generate ng2-charts-schematics:radar charts/product-sales-chart
ng generate ng2-charts-schematics:pie charts/sales-traffic-chart
ng generate ng2-charts-schematics:line charts/annual-sales-chart 
ng generate ng2-charts-schematics:bar charts/store-sessions-chart
an error is thrown: An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

Here is a copy of my package.json
{
  "name": "store-admin-panel",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "^17.2.0",
    "@angular/animations": "^17.2.0",
    "@angular/cdk": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/material": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/router": "^17.2.0",
    "chart.js": "^4.4.1",
    "ng2-charts": "^5.0.4",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.2.0",
    "@angular/cli": "^17.2.0",
    "@angular/compiler-cli": "^17.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ng2-charts-schematics": "^0.1.7",
    "typescript": "~5.3.2"
  }
}
what is causing this error?  I  just created the project with angular 17, added Angular material, ng2-charts and chart.js and was following the demo.

thanks

**Comment by santam85** [comment] 2024-02-29 15:38
> I've updated to v6.0.0-beta.1 and followed the changes in the readme. The charts are displaying however I get the following error in angular cli output every time the chart is rendered. I am using SSR and es-build. Has anyone else experienced this error?
> 
> ERROR Error: NotYetImplemented at exports.nyi (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :474:13) at new _BaseChartDirective (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :27858:38) at NodeInjectorFactory.BaseChartDirective_Factory [as factory] (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :27963:10) at getNodeInjectable (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :6667:38) at instantiateAllDirectives (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :9061:23) at createDirectivesInstances (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :8653:3) at ɵɵelementStart (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :16415:5) at Module.ɵɵelement (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :16459:3) at DayGraphComponent_Conditional_2_Template (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :7167:27) at executeTemplate (eval at instantiateModule (file:///C:/My%20Stuff/Edge/EdgeUI/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), :8626:5)
> 
> Also the readme mentions using withColorGenerator however that doesn't seem to be exported from ng2-charts

can you try to create a minimum reproduction example with SSR for us? I can't seem to reproduce this error in a clean app...

As for the color generation, we removed it from v6 APIs as the functionality is provided directly by Chart.js as of v4 with the Colors plugin.

**Closed by santam85** 2024-02-29 15:38 UTC

**Comment by blakshmibhavani** [comment] 2024-05-03 06:29
> The error is gone, but then when i used it to create a chart component there are issues with the classes(label, chartdatasets) and in html .
> 
> i have imported the chart module into my app and sub module too but of no help. @santam85 ![image](https://private-user-images.githubusercontent.com/36421369/288063110-9e619779-68a7-465a-b60e-5c1ab7d58c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTcyODUsIm5iZiI6MTcxNDcxNjk4NSwicGF0aCI6Ii8zNjQyMTM2OS8yODgwNjMxMTAtOWU2MTk3NzktNjhhNy00NjVhLWI2MGUtNWMxYWI3ZDU4YzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA2MTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MGJlZjZkNTNhZWVhODc5Yzk1M2NjOGUxNDk5ODg1ZjE5ZTM0NWEzNTUxNjJlNjQwNTEzMWQwMzU2ZmRmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZcybjKzOo-rkFj01BgOYwtil9EXha_3y_FIfw6r5ug)

Is ur issue resolved? am also getting the same error      <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
          [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
          [plugins]="SensorlineChartPlugins" (chartHover)="chartClick($event)" *ngIf="isGraphVisible"
          height="360" width="300" style="margin-left: -15px !important; ">
  </canvas>[ng] Error: src/app/tab2/tab2.page.html:107:21 - error NG8002: Can't bind to 'datasets' since it isn't a known property of 'canvas'.
[ng]
[ng] 107   <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
[ng]                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:107:49 - error NG8002: Can't bind to 'options' since it isn't a known property of 'canvas'.
[ng]
[ng] 107   <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
[ng]                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:11 - error NG8002: Can't bind to 'colors' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:44 - error NG8002: Can't bind to 'legend' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:77 - error NG8002: Can't bind to 'chartType' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:109:11 - error NG8002: Can't bind to 'plugins' since it isn't a known property of 'canvas'.
[ng]
[ng] 109           [plugins]="SensorlineChartPlugins" (chartHover)="chartClick($event)" *ngIf="isGraphVisible"
[ng]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           and my package.json is {
  "name": "aquaNew",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.2",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@capacitor/android": "^5.7.0",
    "@capacitor/core": "^5.7.0",
    "@capacitor/ios": "^5.7.0",
    "@capacitor/local-notifications": "^5.0.7",
    "@ionic/angular": "^7.0.0",
    "@microsoft/signalr": "^3.1.11",
    "@types/chart.js": "^2.9.37",
    "angular-gauge-chart": "0.7.2",
    "chart.js": "^2.9.4",
    "chartjs-plugin-annotation": "^0.5.7",
    "ionicons": "^7.0.0",
    "ng2-charts": "^2.4.3",
    "point-in-polygon": "1.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2",
    "@types/d3": "^7.4.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.0",
    "@angular-eslint/builder": "^17.0.0",
    "@angular-eslint/eslint-plugin": "^17.0.0",
    "@angular-eslint/eslint-plugin-template": "^17.0.0",
    "@angular-eslint/schematics": "^17.0.0",
    "@angular-eslint/template-parser": "^17.0.0",
    "@angular/cli": "^17.0.0",
    "@angular/compiler-cli": "^17.0.2",
    "@angular/language-service": "^17.0.2",
    "@capacitor/cli": "^5.7.0",
    "@ionic/angular-toolkit": "^9.0.0",
    "@types/jasmine": "~5.1.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~5.1.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  },
  "description": "An Ionic project"
}

**Comment by blakshmibhavani** [comment] 2024-05-03 06:31
> The 5.x versions of the library will work correctly and should not throw any dependency warning with Angular 17.
> 
> It's migration to 17's build is WIP at https://github.com/valor-software/ng2-charts/tree/angular-17 There are currently issues with some of the upstream dependencies, the ESM build limitations ([angular/angular-cli#26575](https://github.com/angular/angular-cli/issues/26575)), jest testing and some of the Chart.js plugins used in the demos.

    <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
          [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
          [plugins]="SensorlineChartPlugins" (chartHover)="chartClick($event)" *ngIf="isGraphVisible"
          height="360" width="300" style="margin-left: -15px !important; ">
  </canvas>[ng] Error: src/app/tab2/tab2.page.html:107:21 - error NG8002: Can't bind to 'datasets' since it isn't a known property of 'canvas'.
[ng]
[ng] 107   <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
[ng]                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:107:49 - error NG8002: Can't bind to 'options' since it isn't a known property of 'canvas'.
[ng]
[ng] 107   <canvas baseChart [datasets]="SensorlabelMFL" [options]="SensorlineChartOptions"
[ng]                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:11 - error NG8002: Can't bind to 'colors' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:44 - error NG8002: Can't bind to 'legend' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:108:77 - error NG8002: Can't bind to 'chartType' since it isn't a known property of 'canvas'.
[ng]
[ng] 108           [colors]="SensorlineChartColors" [legend]="SensorlineChartLegend" [chartType]="SensorlineChartType"
[ng]                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]   src/app/tab2/tab2.page.ts:27:15
[ng]     27  templateUrl: 'tab2.page.html',
[ng]                      ~~~~~~~~~~~~~~~~
[ng]     Error occurs in the template of component Tab2Page.
[ng]
[ng]
[ng] Error: src/app/tab2/tab2.page.html:109:11 - error NG8002: Can't bind to 'plugins' since it isn't a known property of 'canvas'.
[ng]
[ng] 109           [plugins]="SensorlineChartPlugins" (chartHover)="chartClick($event)" *ngIf="isGraphVisible"
[ng]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           and my package.json is {
  "name": "aquaNew",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.2",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@capacitor/android": "^5.7.0",
    "@capacitor/core": "^5.7.0",
    "@capacitor/ios": "^5.7.0",
    "@capacitor/local-notifications": "^5.0.7",
    "@ionic/angular": "^7.0.0",
    "@microsoft/signalr": "^3.1.11",
    "@types/chart.js": "^2.9.37",
    "angular-gauge-chart": "0.7.2",
    "chart.js": "^2.9.4",
    "chartjs-plugin-annotation": "^0.5.7",
    "ionicons": "^7.0.0",
    "ng2-charts": "^2.4.3",
    "point-in-polygon": "1.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2",
    "@types/d3": "^7.4.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.0",
    "@angular-eslint/builder": "^17.0.0",
    "@angular-eslint/eslint-plugin": "^17.0.0",
    "@angular-eslint/eslint-plugin-template": "^17.0.0",
    "@angular-eslint/schematics": "^17.0.0",
    "@angular-eslint/template-parser": "^17.0.0",
    "@angular/cli": "^17.0.0",
    "@angular/compiler-cli": "^17.0.2",
    "@angular/language-service": "^17.0.2",
    "@capacitor/cli": "^5.7.0",
    "@ionic/angular-toolkit": "^9.0.0",
    "@types/jasmine": "~5.1.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~5.1.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  },
  "description": "An Ionic project"
}
