### ISSUE TITLE
Add way to remove moment from build

### ISSUE THREAD

**Issue by almgwary** [valor-software/ng2-charts#1108] opened 2019-05-06 09:12 UTC
Moment js increase the bundle size, add option to remove it while build

Moment.js is installed along Chart.js as dependency. If you don't want to use Moment.js (either because you use a different date adapter or simply because don't need time functionalities), you will have to configure your bundler to exclude this dependency (e.g. using externals for Webpack or external for Rollup).

https://github.com/chartjs/Chart.js/blob/f2b099b835bf5d6dfe3a7d3097997ec11983c3ed/docs/getting-started/integration.md#L28

**Comment by almgwary** [comment] 2019-05-06 09:50
@paviad check this

**Comment by paviad** [comment] 2019-05-06 10:52
I am not proficient in webpack, moment is indeed a part of chart.js therefore I have no easy way to get rid of it in ng2-charts...

**Comment by almgwary** [comment] 2019-05-06 11:06
You can import standalone version - not bundled one with the following line:

`import Chart from 'chart.js/dist/Chart.js'`

Or setting alias in web.config:
```
resolve: {
    alias: {
      'chart.js': 'chart.js/dist/Chart.js'
    }
}
```

**Comment by paviad** [comment] 2019-05-06 12:32
But I do not include chart.js as a dependency but as a peer dependency - so it is up to the user to include all of chart.js or just the bare package without the bundle.

**Comment by paviad** [comment] 2019-05-07 17:06
So the problem is recreating the game state based on replay data? In theory can we use the existing game DLL's to do that?

**Comment by almgwary** [comment] 2019-05-08 07:40
> But I do not include chart.js as a dependency but as a peer dependency - so it is up to the user to include all of chart.js or just the bare package without the bundle.

you should change the chart.js import at `base-chart.directive`
to be like this

`import * as chartJs from 'chart.js/dist/Chart.bundle.js'`

this should solve the problem

**Comment by naveedahmed1** [comment] 2019-08-29 18:55
Any update on this? This can save 574.32 Kb. With chart.js 2.8 it should now be possible. 
https://github.com/chartjs/Chart.js/pull/5960

I would also like to know if we can also remove lodash.js dependency?

**Comment by M-Blobby** [comment] 2019-08-30 08:36
I'm also interested about any update. I'm in the same situation with naveedahmed1.

**Comment by AceVentura** [comment] 2020-08-18 15:40
Hello,

Any updates on this?

**Comment by almgwary** [comment] 2020-08-19 16:03
> Hello,
> 
> Any updates on this? 

Copy the base directive in your project and apply the following update

https://github.com/valor-software/ng2-charts/issues/1108#issuecomment-490383242

**Comment by paviad** [comment] 2020-08-26 16:22
Wait, what is wrong with this import in `base-chart.directive.ts`:

```javascript
import {
  Chart,
  ChartConfiguration,
  ChartDataSets,
  ChartOptions,
  ChartPoint, ChartType,
  PluginServiceGlobalRegistration,
  PluginServiceRegistrationOptions,
  pluginService
} from 'chart.js';
```

**Comment by AlecDusheck** [comment] 2021-01-06 04:39
You can use a custom webpack configuration to mark `moment` as an external package. This can be accomplished by installing/configuring the `@angular-builders/custom-webpack` package and then including this custom webpack config:
```
module.exports = {
  externals: {
    moment: 'moment',
  },
}

```

**Comment by santam85** [comment] 2024-03-01 16:24
fixed in v3+

**Closed by santam85** 2024-03-01 16:24 UTC
