### ISSUE TITLE
Chart not show when I update to Angular 4

### ISSUE THREAD

**Issue by limjoonae** [valor-software/ng2-charts#709] opened 2017-03-29 02:48 UTC
I install ng2-chart and chart.js in a new project with the current my source code and update Angular to 4.
but chart not show and no error in console. Please give me the troubleshooting :).

**Comment by chrisparton1991** [comment] 2017-03-29 04:22
Probably a duplicate of #707, as the dependencies haven't been updated yet.

**Comment by limjoonae** [comment] 2017-03-30 02:37
Ok. I'm waiting for solution. 
Thank you :D

**Comment by zbagley** [comment] 2017-03-30 14:17
I've updated to Angular v4 without issues except for the NPM warning of required dependencies. My package.json dependencies looks like:

  ```
"dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/router": "4.0.0",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "angular2-google-maps": "^0.17.0",
    "animate.css": "^3.5.1",
    "assets-webpack-plugin": "^3.4.0",
    "bootstrap": "4.0.0-alpha.4",
    "bootstrap-loader": "2.0.0-beta.12",
    "chart.js": "^1.1.1",
    "ckeditor": "4.6.0",
    "core-js": "^2.4.1",
    "extract-text-webpack-plugin": "2.0.0-beta.3",
    "font-awesome": "^4.6.3",
    "font-awesome-sass-loader": "^1.0.2",
    "fullcalendar": "^2.7.2",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "ionicons": "^2.0.1",
    "is-electron-renderer": "^2.0.0",
    "jquery": "^2.2.3",
    "jquery-slimscroll": "^1.3.6",
    "lodash": "^4.12.0",
    "ng2-bootstrap": "^1.3.0",
    "ng2-charts": "^1.5.0",
    "ng2-ckeditor": "1.0.7",
    "ng2-smart-table": "^0.3.2",
    "ng2-tree": "^0.0.2-7",
    "ng2-uploader": "1.1.0",
    "normalize.css": "^4.1.1",
    "postcss-loader": "^1.0.0",
    "rxjs": "5.0.0-beta.12",
    "tether": "^1.2.4",
    "zone.js": "~0.7.1"
  }
```

Are you receiving any other warnings from npm besides those listed in #707? When you load the page do you receive any errors in your developer console?

**Comment by paviad** [comment] 2019-03-05 15:27
Closing for inactivity - if issue persists, feel free to comment with a working example (codepen/plunkr/...) which demonstrates the issue.

**Closed by paviad** 2019-03-05 15:27 UTC
