### ISSUE TITLE
chart Js 3.0 update

### ISSUE THREAD

**Issue by abannsunny** [valor-software/ng2-charts#1214] opened 2020-03-27 16:27 UTC
Hi

I was wondering if there are any plans to update ng2-charts to support the chart.js 3.0 release.

Thank you.

**Comment by danjor38** [comment] 2020-04-16 15:24
It would be nice to upgrade to charts.js 3.0

**Comment by cyberluke** [comment] 2020-05-11 20:21
Copy that!

**Comment by paviad** [comment] 2020-08-25 16:42
@santam85 do you think you can handle this? :)

**Comment by santam85** [comment] 2020-09-04 11:25
@paviad sure thing! If you can get me access to the applitools project (even readonly) It would help a lot to reduce regressions though...

**Comment by paviad** [comment] 2020-09-05 09:35
@santam85 Can we just create new applitools workspace and ditch the old one? Not getting any response from the owner @valorkin

**Comment by santam85** [comment] 2020-09-07 11:29
Sure we can, we'd loose any baseline comparison though...

**Comment by santam85** [comment] 2020-10-08 07:35
Quick update here: I have a working version of the library updated to Chart.js 3.0 beta 3
Will push the WIP to a branch soon for review, because some small changes to the APIs were needed due to breaking changes in Chart.js

**Comment by valorkin** [comment] 2020-10-08 09:47
@santam85 well done!

**Comment by jordancue** [comment] 2020-12-22 01:41
Any update on this issue?

**Comment by santam85** [comment] 2021-01-04 16:09
@jordancue waiting for https://github.com/chartjs/chartjs-plugin-datalabels/issues/180

**Comment by schwenkreis** [comment] 2021-02-10 06:55
Sorry, I did not recognize this issue. Please close #1292 and thanks a lot for working on this!

**Comment by 7amou3** [comment] 2021-03-21 14:08
hello, any news on charjs v3?

**Comment by santam85** [comment] 2021-03-21 17:01
> hello, any news on charjs v3?

Have a look at PR https://github.com/valor-software/ng2-charts/pull/1276
The Chart.js team has just released rc.2, and work has been done on the datalabels and annotation plugins (on which this library depends on) to make them compatible. Only a couple of visual tests are now failing (mostly related to the annotation plugin), but I expect to be able to quickly fix everything after the final 3.0 version of chart.js is out.

**Comment by jordankkk** [comment] 2021-04-03 10:11
3.0 is released :smiley:

**Comment by vibonacci** [comment] 2021-04-08 10:18
Is it safe to use the dev-3 branch? The PR seems approved.

**Comment by santam85** [comment] 2021-04-08 10:21
@vibonacci not all dependencies have a stable and released Chart.js v3.0 compatible version (datalabel and financial charts), but in general what's on the branch works correclty.
I am in the process of getting it released under the `next` tag, while I finish up documentation work and the transitive deps release a final version.

**Comment by SteveKennedy** [comment] 2021-04-15 23:59
How would I go about using dev-3 in my package.json? 

I have: "ng2-charts": "valor-software/ng2-charts#dev-3"

But when I run npm install, it eventually errors with: Not Found - GET https://registry.npmjs.org/chartjs-chart-financial - Not found

**Comment by santam85** [comment] 2021-04-16 09:20
> How would I go about using the dev-3 branch in my package.json?
> 
> I have: "ng2-charts": "valor-software/ng2-charts#dev-3"
> 
> But when I run npm install, it eventually errors with: Not Found - GET https://registry.npmjs.org/chartjs-chart-financial - Not found

Unfortunately specifying the dependency like that will not work as the repo is currently using a git submodule. I am ready to push the required changes to make it work, but we need https://github.com/chartjs/chartjs-chart-financial/pull/95 to be merged first, as there isn't any compatible release of that library.

Manual checkout and linking is needed if you want to test this branch.

**Comment by redsuperbat** [comment] 2021-04-24 15:51
Hello! 
Any news on this update? Anything I can do to thelp?
Best Reagards

**Comment by santam85** [comment] 2021-04-26 12:40
> Hello!
> Any news on this update? Anything I can do to thelp?
> Best Reagards

Hey there, mainly https://github.com/chartjs/chartjs-chart-financial/pull/95, and access for me to publish this on NPM

**Closed** 2021-04-29 07:19 UTC
