### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by mshubhamtyagi** [valor-software/ng2-charts#1117] opened 2019-06-05 08:14 UTC
**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related to Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is an issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project and shows in an
![Screenshot from 2019-06-05 13-27-55](https://user-images.githubusercontent.com/21307943/58940767-02026180-8798-11e9-9e32-0c2acb96ae83.png)
 the ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by fermedina** [comment] 2019-06-05 11:54
The same issue

**Comment by mix5003** [comment] 2019-06-05 12:36
i think it like #1115.
try `npm install ng2-charts@~2.2.5`, and run agian

**Comment by ellieraya** [comment] 2019-06-05 22:09
Hi,

I have ng chart in production and I am facing the same issue. Can somebody  suggest for solutions asap.
_

**Comment by tranvannhat** [comment] 2019-06-06 02:39
with me, i edit code in `./node_modules/ng2-charts/fesm5/ng2-charts.js` find and replace `ɵɵdefineInjectable` to `defineInjectable`. It's working with me, but i don't want edit lib, can you update lib?

**Comment by DeepaliMadge** [comment] 2019-06-10 05:23
same error.

**Comment by raksha-rathore** [comment] 2019-06-10 18:25
i am also facing this error. anyone got the solution?

**Comment by RbkGh** [comment] 2019-06-11 17:55
same issue here too.any appropriate fix aside editing ɵɵdefineInjectable in library?

**Comment by raksha-rathore** [comment] 2019-06-11 20:12
i used the older release 2.2.0 and the issue is not coming there. earlier i was using 2.2.4 version. I have not tried 2.2.5.
For now my code is working with 2.2.0 version

**Comment by RbkGh** [comment] 2019-06-11 20:14
I just realized any version <=2.2.3 works.
So just open package.json and update ng2-charts version accordingly.

**Comment by naysumyat** [comment] 2019-06-12 02:40
2.2.5 works for me.

**Comment by abalad** [comment] 2019-06-12 13:53
`npm install ng2-charts@~2.2.5 --save` works for me

**Comment by amitvermaknw** [comment] 2019-06-26 16:53
I agree with @tranvannhat , I also edit the code  in ./node_modules/ng2-charts/fesm5/ng2-charts.js  and replace ɵɵdefineInjectable to defineInjectable and it's working fine. ng2-chart team can you update this? As we are using this lib in prod and while building on prod I cannot push my local lib it will fetch from repo.

**Comment by bryplano** [comment] 2019-06-26 22:45
As a few folks have noted, I was able to update to v2.2.5 and this issue was fixed in an Angular 7 project:

```
npm install ng2-charts@2.2.5 --save
```

The error popped up after there was a change to build this project (ng2-charts) with Angular 8. That change was reverted with Release v2.2.5: https://github.com/valor-software/ng2-charts/releases/tag/2.2.5

v2.3.0 has been upgraded to use Angular 8 or Angular 7: https://github.com/valor-software/ng2-charts/commit/ec5e6038ae4d1a94737340b00397175324491028#diff-e86dda6566477895fbf685c476288762

Angular's official repo has an issue on this type of error if you're interested: https://github.com/angular/angular/issues/30413

**Comment by rcrodrigues** [comment] 2019-06-27 21:55
@bryplano I've just updated ng2-charts to v2.3.0 on an Angular 8 project, and this error popped up as well.

**Comment by bryplano** [comment] 2019-06-27 22:35
@rcrodrigues thanks for checking! Shame the change broke this (and other) libs, but it sounds like it's intended per this post: https://github.com/angular/angular/issues/30413#issuecomment-491683547

> Given all the above, I don't see how this issue is actionable, so I'll go ahead and close this. My advise would be to keep building your library using the minimally required Angular version.

Guess sticking at 2.2.5 is currently advisable @rcrodrigues :\

**Comment by thefliik** [comment] 2019-06-30 00:10
For those interested, upgrading my app to Angular `v8` and using ng2-charts `v2.3.0` fixes this issue for me. 

As indicated in the helpfully linked [angular/angular#30413](https://github.com/angular/angular/issues/30413), this issue was caused by compiling this library using the Angular v8 compiler. Libraries which support either Angular `v7 || v8` must be compiled using angular `v7`.

**Comment by makasanas** [comment] 2019-08-09 10:58
npm install ng2-charts@~2.2.5 --save work for me

**Closed** 2020-01-17 07:57 UTC

**Comment by s-ramesh** [comment] 2020-09-30 06:56
I am also facing the same issue I upgrade tp 2.2.5 ng serve works fine but ng build it is showing the same error "Uncaught TypeError: Object(...) is not a function" any one help asap.

**Comment by paviad** [comment] 2020-09-30 18:57
I just created a fresh angular app using `@angular/cli@^8.0.0` and imported `ChartsModule` from `ng2-charts@2.4.2` - no problems. It's not the angular version, or the library... something else in your setup is the issue.

**Comment by gooligari** [comment] 2021-12-22 08:35
i am getting ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function while implementing ng2-charts. I tried with Below versions but nothing is helping. Thanks in advance.
ng2-charts : 2.2.0 & 2.2.5 & 2.2.4 & 2.4.2
Angular : 5
"chart.js": "^2.9.3",
