### ISSUE TITLE
The generateLegend() method exists on the Chart object so we can access it by grabbing it from the Viewchild of the BaseChartDirective like so

### ISSUE THREAD

**Issue by paragkulkarni** [valor-software/ng2-charts#1363] opened 2021-12-24 13:07 UTC
**How to do this in ng2-chart version -3.0**

The generateLegend() method exists on the Chart object so we can access it by grabbing it from the Viewchild of the BaseChartDirective like so

`    @ViewChild(BaseChartDirective) private _chart: BaseChartDirective;

    public ngOnInit(): void {
        this._chart.chart.generateLegend();
        
    }`

But i'm yet to have luck creating a custom legend

_Originally posted by @aidanbiggs in https://github.com/valor-software/ng2-charts/issues/1109#issuecomment-527974619_

**Comment by santam85** [comment] 2022-01-05 14:33
Duplicate of #1362

**Closed by santam85** 2022-01-05 14:33 UTC
