### ISSUE TITLE
ng2-charts don't show 

### ISSUE THREAD

**Issue by sadydai** [valor-software/ng2-charts#330] opened 2016-07-27 07:16 UTC
export class ChartComponent {
    // lineChart
    public lineChartData:Array<any> = [
        {data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A'},
        {data: [28, 48, 40, 19, 86, 27, 90], label: 'Series B'},
        {data: [18, 48, 77, 9, 100, 27, 40], label: 'Series C'}
    ]; public lineChartLabels:Array<any> = ['January', 'February', 'March', 'April', 'May', 'June', 'July'];
.....
in html :
but can't get the canvas;
"base-chart class="chart" ng-reflect-datasets="# [object Object],[object Object],[object Object]" ng-reflect-labels="January,February,March,April,May,June,July" ng-reflect-options="[object Object]" ng-reflect-chart-type="line" ng-reflect-colors="[object Object],[object Object],[object Object]" ng-reflect-legend="true"

**Comment by bushev** [comment] 2016-07-27 13:30
The same for me. Canvas is empty..


<img width="1009" alt="screenshot 2016-07-27 16 28 29" src="https://cloud.githubusercontent.com/assets/7535766/17176885/6d419b62-5417-11e6-8d12-52e7e2aa3c20.png">

**Comment by bushev** [comment] 2016-07-27 13:48
I think this is a duplication of https://github.com/valor-software/ng2-charts/issues/229

**Comment by sadydai** [comment] 2016-07-28 08:59
@bushev   yes ;   set  .chart {display: block; width: 100%;}   .then it shows

**Comment by bushev** [comment] 2016-07-28 11:29
@sadydai Unfortunately, it was not help me. I switched to use a pure Chart.js

**Comment by Hongbo-Miao** [comment] 2016-07-29 17:04
@bushev maybe add a reproduction:

Check this ng2-charts starting template: http://plnkr.co/edit/7fGsiuRjcF0M0Ffeoml2?p=preview
It may help you show the charts.

**Comment by dragGH102** [comment] 2016-08-01 11:18
Just add chart class (as in the exmples) and make sure to pass the necessary options (the ones from example work fine):

.chart {
  display: block; // or inline-block
  width: 100%;
  height: 100%;
}

**Comment by atorefrank** [comment] 2016-08-27 00:58
Do folks still have an issue with ng2-charts. I have been able to get it to work, all I trying to figure now is how to chart data from a REST API url.

**Comment by Hongbo-Miao** [comment] 2016-08-30 05:16
Since it is duplicated with https://github.com/valor-software/ng2-charts/issues/229, I will close it now.

**Closed by Hongbo-Miao** 2016-08-30 05:16 UTC

**Comment by atorefrank** [comment] 2016-08-30 12:22
Sounds good. I was able to get the chart to show up, however I am now
having issues trying to get it to display data from a REST API.
ᐧ

**Comment by Hongbo-Miao** [comment] 2016-08-30 15:35
@atorefrank I think because the Change Detection dose not run.

Check these
https://github.com/valor-software/ng2-charts/issues/291
https://github.com/valor-software/ng2-charts/issues/378
