### ISSUE TITLE
Cannot read property skip of undefined

### ISSUE THREAD

**Issue by NickSterckx** [valor-software/ng2-charts#509] opened 2016-11-18 10:57 UTC
I am having issues with allowing the application to dynamically update, and have been getting an error that breaks functionality since I've updated to the latest release.

The full error is as follows:

```
error_handler.js:54 TypeError: Cannot read property 'skip' of undefined
    at e (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:21038)
    at a (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:21083)
    at n (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:21455)
    at t.Controller.getElementsAtEventForMode (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:11:31846)
    at t.Controller.handleEvent (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:1869)
    at t.Controller.eventHandler (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:1491)
    at t.Controller.eval (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:1168)
    at HTMLCanvasElement.i.(anonymous function) (eval at module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:12:17204)
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:98364:35)
    at Object.onInvokeTask (http://localhost:4200/main.bundle.js:30045:37)

ErrorHandler.handleError	@	error_handler.js:54
next	@	application_ref.js:298
schedulerFn	@	async.js:89
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:223
SafeSubscriber.next	@	Subscriber.js:172
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	async.js:81
NgZone.triggerError	@	ng_zone.js:280
onHandleError	@	ng_zone.js:259
ZoneDelegate.handleError	@	zone.js:236
Zone.runTask	@	zone.js:157
ZoneTask.invoke	@	zone.js:335
```

This error occurs after hovering any component of the chart after I've tried to update the background data. This interaction does update the chart a single time, but then makes it unfunctional.

I am trying to initially fetch, then periodically update data as follows:

```
ngOnInit(): void {
        this.fetchdata();
        let timer = Observable.timer(10000, 10000);
        timer.subscribe(() => this.addData());
    }

    fetchdata() {
        this.dbService.retrieveSystemData().subscribe(response => {
            this.lineChartData = [{data: [response.value], label: 'label'}];
            this.lineChartLabels = [response.label];
        });
    }

    addData() {

        this.dbService.retrieveSystemData().subscribe(response => {
            this.lineChartData[0].data.push(response.value);
            this.lineChartLabels.push(response.label);
        });

    }
```

I have already verified data is being fetched correctly, and should be updated to a format that is still compatible with the chart functionality. Is this a bug, or an error on my part? 

Here is the html for good measure:

```
<div class="chart-wrapper">
            <canvas baseChart class="chart" [datasets]="lineChartData" [labels]="lineChartLabels" [options]="lineChartOptions" [legend]="lineChartLegend" [chartType]="lineChartType" ></canvas>
        </div>
```

**Comment by frosenberg** [comment] 2016-11-27 19:37
I'm seeing the same issue but it is not happening all the time. Looks like a race condition.

**Comment by arimus** [comment] 2016-12-14 03:58
I was getting this error very consistently (but not always) as you say. Comparing versions of chart.js I determined I was using 2.4.0 instead of 2.3.0 like ng2-charts itself is using. 

Downgrading to 2.3.0, I no longer see this issue.

**Comment by fyyyyy** [comment] 2017-04-13 14:51
Downgrade to 2.3.0 fixed it ! Especially when using this https://github.com/hchstera/vue-charts library as it frequently reassigns data.

**Comment by philjones88** [comment] 2017-04-21 14:16
I've been hitting this too with 2.5.0 of Chart.JS and 1.5.0 of ng2-charts.

**Comment by theunreal** [comment] 2017-06-09 16:38
I have this error in any version of chart.js

**Comment by Tyldar** [comment] 2017-06-10 14:42
@theunreal I had the same problem, i'm just using an *ngIf to hide the chart until the datas are loaded properly :)

**Comment by darulAbror** [comment] 2017-06-12 01:07
me too, i got the same issue, and I dont know how to deal with it

**Comment by lucasmncastro** [comment] 2017-10-07 20:13
Thanks @Tyldar!  Your solution worked for me. I just put the *ngIf and the issue has gone.

```html
 <canvas baseChart *ngIf="lineChartData"
                [datasets]="lineChartData"
                [labels]="lineChartLabels"
                [options]="lineChartOptions"
                [colors]="lineChartColors"
                [legend]="lineChartLegend"
                [chartType]="lineChartType"
                (chartHover)="chartHovered($event)"
                (chartClick)="chartClicked($event)"></canvas>
```

I am using version ng2-charts 1.6.0.

**Comment by paviad** [comment] 2019-03-05 22:32
This issue appears to be closed. Package is now updated for Angular 7. If this issue persists please provide a stackblitz/codepen/... example which reproduces it.

**Closed by paviad** 2019-03-05 22:32 UTC
