### ISSUE TITLE
scale type "time" with version 3+

### ISSUE THREAD

**Issue by doczoidberg** [valor-software/ng2-charts#1367] opened 2022-01-05 12:19 UTC
does version 3+ work with time as type?
```
options=
  scales: {
      x: {
          type: 'time',
...
```

older versions on stackblitz do work with `time` as type but I can't to get it to work with 3+ and angular 13.

**Comment by santam85** [comment] 2022-01-05 14:28
Duplicate of #1366

**Closed by santam85** 2022-01-05 14:28 UTC
