### ISSUE TITLE
Bar Chart Labels Dynamically Change Not Work ng2-charts 1.5.0

### ISSUE THREAD

**Issue by caglarturkurka** [valor-software/ng2-charts#718] opened 2017-04-01 13:14 UTC
Hi I want to change labels of Barchart dynamically (getting from async request), but this feature does not work at version 1.5.0. For that reason I have to use version of 1.4.4. Please can you solve this problem for 1.5.0 version or please tell me can I solve that problem with version 1.5.0

**Comment by bloArribas** [comment] 2017-04-02 20:43
Same here, labels won't update.

**Comment by 5f6b3fb8** [comment] 2017-04-05 17:12
Confirmed caglarturkurka's findings. Downgrade to 1.4.4 fixed my issue.

**Comment by Dawlys** [comment] 2017-04-06 09:47
👍

**Comment by vicjohnson1213** [comment] 2017-04-12 17:02
@valorkin Are there any plans to fix this in v1.5.x or 1.6? It does work in v1.4.4 and I've seen a few pull requests on the subject in other issues but I don't know what has happened to those.

**Comment by grahammutter** [comment] 2017-04-12 18:21
Having the same issue. Took a look through the code, the ngOnChanges logic explicitly only updates the datasets property. @vicjohnson1213: Can you link me the pull-requests you've seen that address these? I've been unable to find them. If none of them are sufficient I'll write up a fix.

@valorkin: If a fix for this is already in the pipeline please let me know, otherwise I'll submit a pull request shortly.

**Comment by vicjohnson1213** [comment] 2017-04-12 18:54
@grahammutter After a little more research I think all of the pull request I've seen were for 1.4.4 and earlier.  That being said, [ngOnChanges for v1.4.4] handles labels as well as datasets.  It looks like it was removed in the process of refactoring.

**Comment by valorkin** [comment] 2017-04-13 06:09
I will appreciate any help with this project, 
actually I am looking for maintainers :)

**Comment by valorkin** [comment] 2017-04-13 09:20
My main focus is v2 of ngx-bootstrap

**Comment by grahammutter** [comment] 2017-04-20 20:59
@valorkin I'll address this and a few other feature requests starting ~April 26th. Wrapping up a sprint at work which includes fixes to a few of these (plus some other enhancements) that I'll port back once I'm done.

**Comment by malikasinger1** [comment] 2017-05-05 11:15
@valorkin I have a friend who is interested in maintaining your repo,
contact me on skype: malikasinger111

**Comment by Markus-ipse** [comment] 2017-05-30 14:52
Based on just the titles at least half of the open PRs at the moment relate to the charts not updating properly, so until @valorkin either finds time or a maintainer there's probably not much use to open yet another PR (unless it solves a different problem than the existing ones).

**Comment by thor089** [comment] 2017-08-21 11:32
Unfortunately it took me a while to finde the reason for my issues.
But then I also notices that the dynamic update of the labels is broken.
In my scenario the charts are uselsess without the dynamic change of the labels.
They were working extremely good before... I will also downgrade. ;-(
I realy would appreciate a fix. - I think this fork is addressing the issue: https://github.com/amolghotankar/ng2-charts/commit/697dabe9df5a7b7d221bdb776e2ffbe3ceeb2322

**Comment by maxmumford** [comment] 2018-06-07 12:34
Without a reproduction plnkr it's difficult to know if we're facing the same issue, but in version 1.6.0 I've been able to get data set and label change animations working by changing them separately. Ie:

 - trigger an async request
 - in the subscription, update data sets
 - then use setTimeout(.., 0) to update the labels afterwards

https://giphy.com/gifs/5UKCQ9fbyDpOk1Oq6N

**Comment by paviad** [comment] 2019-03-09 12:42
This package has been updated for Angular 7 with many bug fixes and enhancements. In particular see the [demo app](https://valor-software.com/ng2-charts) under *Pie Chart* to see dynamic label changes triggered by a button click. If this issue persists feel free to reopen with a stackblitz example.

**Closed by paviad** 2019-03-09 12:42 UTC
