### ISSUE TITLE
Trying to achieve zoomooz plugin like functionality in Angular

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#985] opened 2018-05-10 05:21 UTC
**Reproduction of the problem**

Trying to achieve [zoomooz ](http://jaukia.github.io/zoomooz/)plugin like functionality in Angular . Since npm does not support zoomooz. Is it possible to have same functionality i.e. animated zoom on click. I am using Angular 6 with ng2 charts and want to zoom the div/canvas section on click and back to normal

Refer demo url here https://stackblitz.com/edit/ng2-chart-example

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by paviad** [comment] 2019-03-09 13:38
Possible duplicate of https://github.com/valor-software/ng2-charts/issues/388

Please follow discussion there.

**Closed by paviad** 2019-03-09 13:38 UTC
